build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.9.0
    entrypoint: [""]
  script:
  - |
    cat > /kaniko/.docker/config.json <<EOF
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth":"${DOCKER_AUTH}"
        },
        "${CI_REGISTRY}": {
          "username": "${CI_REGISTRY_USER}",
          "password": "${CI_REGISTRY_PASSWORD}"
        }
      }
    }
    EOF
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination koehn/openvpn:$CI_COMMIT_TAG --build-arg GIT_BRANCH=$(echo $CI_COMMIT_TAG | awk -F '-' '{print $1}') --build-arg SCANNER_TOKEN=$SCANNER_TOKEN
  only: 
  - tags
