#!/bin/bash

set -e

IMAGE_NAME=koehn/openvpn

docker build -t $IMAGE_NAME:latest --build-arg GIT_COMMIT=`git log -1 --format=%h` .

VERSION=`docker run --rm -it $IMAGE_NAME:latest openvpn --version | head -1 | awk '{print $2}'`

docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION

docker push $IMAGE_NAME:latest
docker push $IMAGE_NAME:$VERSION
